apiVersion: v2
name: spring-6-rest-mvc-kafka
description: A Helm subchart for kafka
type: application
# Disable Sonar warning for invalid semver: This value is set by Maven filtering
# and will be replaced with a valid version number during the build process.
version: @helm.chart.version@
appVersion: "4.1.1"
