global:
  namespace: spring-6-rest-mvc

mysql:
  port: 3306
  targetPort: 3306
  nodePort: 30306
  
  database: "restmvcdb"

  user: restadmin
  password: password

  rootPassword: verysecret

mysqlImage:
  repository: mysql
  tag: "8.4.8"
  pullPolicy: IfNotPresent
