apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
spec:
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
  ports:
    - protocol: TCP
      port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
      name: broker
      {{- if and (eq (.Values.kafka.service.type | default "ClusterIP") "NodePort") (.Values.kafka.service.nodePort) }}
      nodePort: {{ .Values.kafka.service.nodePort }}
      {{- end }}
  type: {{ .Values.kafka.service.type | default "ClusterIP" }}